services:
  digimeter:
    image: digimeter:latest
    build:
      context: ..
      dockerfile: docker/digimeter/Dockerfile
    env_file:
      - ../environment.docker.env
    secrets:
      - influx_password

secrets:
  influx_password:
    file: ./secrets/INFLUX_PASSWORD